name: Build

on:
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build project
      env:
        SERVER_USERNAME: il.nur86
      run: echo ${env.SERVER_USERNAME}